spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autocomplete
    password: ${PGPASSWORD}
    username: ${PGUSERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    filter:
      order: 10
  flyway:
    baseline-on-migrate: true
server:
  port: 8081
  servlet:
    context-path: /backend
